# MCSOS Bootloader Configuration (Milestone 2)

# Jangan tunggu menu boot, langsung jalankan kernel
timeout: 0

# Aktifkan output serial agar pesan bootloader muncul di terminal
serial: yes

# Definisi Entry Boot
/MCSOS 260502 M2
    # Gunakan protokol Limine untuk memuat kernel 64-bit
    protocol: limine
    
    # Lokasi kernel di dalam image ISO (folder /boot/)
    path: boot():/boot/kernel.elf
    
    # Argumen baris perintah untuk kernel (bisa dibaca kernel nanti)
    cmdline: mcsos.version=260502 mcsos.milestone=M2 console=serial
